AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloufFormation Template for project_name

Parameters:
  LineChannelAccessToken: {Type: "String", Description: "LINE のアクセストークン"}
  LineChannelSecret: {Type: "String", Description: "LINE のチャンネルシークレット"}

Resources:
  EndPointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: src/lambda1
      Handler: lambda_handler.lambda_handler
      Environment: {Variables: {
        LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken,
        LINE_CHANNEL_SECRET: !Ref LineChannelSecret,
      }}
      Events:
        API:
          Type: Api
          Properties:
            Path: /api_endpoint
            Method: post

Outputs:
  ApiEndpointURL:
    Description: API Endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}/api_endpoint"
